//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public articulo()
        {
            this.stock_deposito = new HashSet<stock_deposito>();
            this.linea_de_compra = new HashSet<linea_de_compra>();
            this.linea_de_ventas = new HashSet<linea_de_ventas>();
            this.tanque = new HashSet<tanque>();
        }
    
        public int id_articulo { get; set; }
        public string codigo_barra { get; set; }
        public string descripcion { get; set; }
        public double precio_unitario { get; set; }
        public double precio_venta_menor { get; set; }
        public double precio_venta_mayor { get; set; }
        public double itc { get; set; }
        public double th_ti { get; set; }
        public double iva { get; set; }
        public double utilidad { get; set; }
        public double stock_critico_gral { get; set; }
        public double stock_actual_gral { get; set; }
        public System.DateTime fecha_stock_actual { get; set; }
        public System.DateTime fecha_registrado { get; set; }
        public int RUBRO_id_rubro { get; set; }
        public bool granel { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<stock_deposito> stock_deposito { get; set; }
        public virtual rubro rubro { get; set; }
        public virtual ICollection<linea_de_compra> linea_de_compra { get; set; }
        public virtual ICollection<linea_de_ventas> linea_de_ventas { get; set; }
        public virtual ICollection<tanque> tanque { get; set; }
    }
}
