//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int id_asistencia { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_entrada { get; set; }
        public System.TimeSpan hora_salida { get; set; }
        public byte[] imagen { get; set; }
        public int EMPLEADO_id_empleado { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
