//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.ventas = new HashSet<ventas>();
        }
    
        public int id_cliente { get; set; }
        public string razon_social { get; set; }
        public string nombre_contacto { get; set; }
        public string cuit { get; set; }
        public string telefono_fijo { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_registrado { get; set; }
        public int CONDICION_DE_IVA_id_condicion_iva { get; set; }
        public int PROVINCIA_id_provincia { get; set; }
    
        public virtual condicion_de_iva condicion_de_iva { get; set; }
        public virtual provincia provincia { get; set; }
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
