//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class condicion_de_iva
    {
        public condicion_de_iva()
        {
            this.cliente = new HashSet<cliente>();
            this.proveedor = new HashSet<proveedor>();
        }
    
        public int id_condicion_iva { get; set; }
        public string descripción { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<proveedor> proveedor { get; set; }
    }
}
