//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.asistencia = new HashSet<asistencia>();
            this.grupo_familiar = new HashSet<grupo_familiar>();
            this.liquidacion = new HashSet<liquidacion>();
            this.logistica = new HashSet<logistica>();
        }
    
        public int id_empleado { get; set; }
        public int legajo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string cargo { get; set; }
        public string dni { get; set; }
        public string cuil { get; set; }
        public string sexo { get; set; }
        public string telefono_fijo { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_egreso { get; set; }
        public System.DateTime fecha_registrado { get; set; }
        public string obra_social { get; set; }
        public int USUARIO_id_usuario { get; set; }
        public int PROVINCIA_id_provincia { get; set; }
        public int CATEGORIA_id_categoria { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<asistencia> asistencia { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual provincia provincia { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<grupo_familiar> grupo_familiar { get; set; }
        public virtual ICollection<liquidacion> liquidacion { get; set; }
        public virtual ICollection<logistica> logistica { get; set; }
    }
}
