//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_familiar
    {
        public int id_grupo_familiar { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string parentesco { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string dni { get; set; }
        public System.DateTime fecha_registrado { get; set; }
        public int Empleado_id_empleado { get; set; }
        public string estado { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
