//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_acceso_usuarios
    {
        public int id_historial_acceso_usario { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_ingreso { get; set; }
        public System.TimeSpan hora_salida { get; set; }
        public int USUARIO_id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
