//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class linea_de_ventas
    {
        public linea_de_ventas()
        {
            this.ventas = new HashSet<ventas>();
        }
    
        public int id_linea_ventas { get; set; }
        public int cantidad { get; set; }
        public double precio_vta { get; set; }
        public double itcVenta { get; set; }
        public string th_tiVenta { get; set; }
        public int ARTICULO_id_articulo { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
