//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class linea_de_liquidacion
    {
        public double cantidad_concepto { get; set; }
        public double importe_concepto { get; set; }
        public int LIQUIDACION_id_liquidacion { get; set; }
        public int CONCEPTO_id_concepto { get; set; }
    
        public virtual concepto concepto { get; set; }
        public virtual liquidacion liquidacion { get; set; }
    }
}
