//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class liquidacion
    {
        public liquidacion()
        {
            this.linea_de_liquidacion = new HashSet<linea_de_liquidacion>();
        }
    
        public int id_liquidacion { get; set; }
        public string periodo { get; set; }
        public System.DateTime fecha_liquidación { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string lugar_de_pago { get; set; }
        public string estado { get; set; }
        public int EMPLEADO_id_empleado { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual ICollection<linea_de_liquidacion> linea_de_liquidacion { get; set; }
    }
}
