//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad
    {
        public localidad()
        {
            this.ubicacion = new HashSet<ubicacion>();
        }
    
        public int id_localidad { get; set; }
        public string codigo_postal { get; set; }
        public string nombre { get; set; }
        public int PROVINCIA_id_provincia { get; set; }
    
        public virtual provincia provincia { get; set; }
        public virtual ICollection<ubicacion> ubicacion { get; set; }
    }
}
