//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class logistica
    {
        public logistica()
        {
            this.ventas = new HashSet<ventas>();
        }
    
        public int id_logistica { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string observaciones { get; set; }
        public int CAMION_id_Camion { get; set; }
        public int EMPLEADO_id_empleado { get; set; }
        public int USUARIO_id_usuario { get; set; }
        public int PROVINCIA_id_provincia { get; set; }
    
        public virtual camion camion { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual provincia provincia { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
