//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eebEntities : DbContext
    {
        public eebEntities()
            : base("name=eebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<articulo> articulo { get; set; }
        public DbSet<asistencia> asistencia { get; set; }
        public DbSet<camion> camion { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<compra> compra { get; set; }
        public DbSet<concepto> concepto { get; set; }
        public DbSet<condicion_de_iva> condicion_de_iva { get; set; }
        public DbSet<deposito> deposito { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<grupo_familiar> grupo_familiar { get; set; }
        public DbSet<historial_acceso_usuarios> historial_acceso_usuarios { get; set; }
        public DbSet<linea_de_compra> linea_de_compra { get; set; }
        public DbSet<linea_de_ventas> linea_de_ventas { get; set; }
        public DbSet<liquidacion> liquidacion { get; set; }
        public DbSet<localidad> localidad { get; set; }
        public DbSet<logistica> logistica { get; set; }
        public DbSet<pago> pago { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<provincia> provincia { get; set; }
        public DbSet<punto_de_venta> punto_de_venta { get; set; }
        public DbSet<recordatorio> recordatorio { get; set; }
        public DbSet<rubro> rubro { get; set; }
        public DbSet<stock_deposito> stock_deposito { get; set; }
        public DbSet<tanque> tanque { get; set; }
        public DbSet<ubicacion> ubicacion { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<ventas> ventas { get; set; }
        public DbSet<linea_de_liquidacion> linea_de_liquidacion { get; set; }
    }
}
