//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int id_pago { get; set; }
        public string nro_comprobante { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string tipo { get; set; }
        public double monto { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
        public int VENTAS_id_venta { get; set; }
    
        public virtual ventas ventas { get; set; }
    }
}
