//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincia
    {
        public provincia()
        {
            this.cliente = new HashSet<cliente>();
            this.empleado = new HashSet<empleado>();
            this.localidad = new HashSet<localidad>();
            this.logistica = new HashSet<logistica>();
            this.proveedor = new HashSet<proveedor>();
        }
    
        public int id_provincia { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual ICollection<localidad> localidad { get; set; }
        public virtual ICollection<logistica> logistica { get; set; }
        public virtual ICollection<proveedor> proveedor { get; set; }
    }
}
