//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class punto_de_venta
    {
        public punto_de_venta()
        {
            this.ventas = new HashSet<ventas>();
        }
    
        public int id_punto_venta { get; set; }
        public string nro_PtoVta { get; set; }
        public string maquina { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
