//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class recordatorio
    {
        public recordatorio()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_funcion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
