//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubro
    {
        public rubro()
        {
            this.articulo = new HashSet<articulo>();
        }
    
        public int id_rubro { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<articulo> articulo { get; set; }
    }
}
