//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_deposito
    {
        public int ARTICULO_id_articulo { get; set; }
        public int DEPOSITO_id_deposito { get; set; }
        public double stock_actual { get; set; }
        public System.DateTime fecha_stock_actual { get; set; }
        public double stock_critico { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual deposito deposito { get; set; }
    }
}
