//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanque
    {
        public int id_tanque { get; set; }
        public string descripcion { get; set; }
        public double capacidad { get; set; }
        public double stock_critico { get; set; }
        public double stock_actual { get; set; }
        public System.DateTime fecha_stock_actual { get; set; }
        public double stock_medicion { get; set; }
        public System.DateTime fecha_medicion { get; set; }
        public int ARTICULO_id_articulo { get; set; }
        public string estado { get; set; }
    
        public virtual articulo articulo { get; set; }
    }
}
