//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public int id_ubicacion { get; set; }
        public int casa { get; set; }
        public string manzana { get; set; }
        public string calle { get; set; }
        public string barrio { get; set; }
        public string sector { get; set; }
        public string zona { get; set; }
        public string departamento { get; set; }
        public string piso { get; set; }
        public int LOCALIDAD_id_localidad { get; set; }
    
        public virtual localidad localidad { get; set; }
    }
}
