//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.compra = new HashSet<compra>();
            this.empleado = new HashSet<empleado>();
            this.historial_acceso_usuarios = new HashSet<historial_acceso_usuarios>();
            this.logistica = new HashSet<logistica>();
            this.ventas = new HashSet<ventas>();
            this.recordatorio = new HashSet<recordatorio>();
        }
    
        public int id_usuario { get; set; }
        public string nombre_usario { get; set; }
        public string contraseña { get; set; }
        public string perfil { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<compra> compra { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual ICollection<historial_acceso_usuarios> historial_acceso_usuarios { get; set; }
        public virtual ICollection<logistica> logistica { get; set; }
        public virtual ICollection<ventas> ventas { get; set; }
        public virtual ICollection<recordatorio> recordatorio { get; set; }
    }
}
