//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public ventas()
        {
            this.pago = new HashSet<pago>();
        }
    
        public int id_venta { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_comp { get; set; }
        public string numero_comp { get; set; }
        public int PUNTO_DE_VENTA_id_punto_venta { get; set; }
        public int CLIENTE_id_cliente { get; set; }
        public int USUARIO_id_usuario { get; set; }
        public int LINEA_DE_VENTAS_id_linea_ventas { get; set; }
        public int LOGISTICA_id_logistica { get; set; }
        public string estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual linea_de_ventas linea_de_ventas { get; set; }
        public virtual logistica logistica { get; set; }
        public virtual ICollection<pago> pago { get; set; }
        public virtual punto_de_venta punto_de_venta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
